---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.sshd"
      ansible.builtin.include_role:
        name: "wandansible.sshd"
      vars:
        sshd_modern: >-
          {{ true if
          (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('20.04', '>=')) or
          (ansible_distribution == "Debian" and ansible_distribution_version is version('11', '>='))
          else false }}

        sshd_config: |
          {% if sshd_modern %}
          Include /etc/ssh/sshd_config.d/*.conf
          {% endif %}

          # Supported HostKey algorithms by order of preference.
          HostKey /etc/ssh/ssh_host_ed25519_key
          HostKey /etc/ssh/ssh_host_rsa_key
          HostKey /etc/ssh/ssh_host_ecdsa_key

          KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

          Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

          MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

          # Password based logins are disabled - only public key based logins are allowed.
          AuthenticationMethods publickey

          # LogLevel VERBOSE logs user's key fingerprint on login. Needed to have a clear audit track of
          # which key was using to log in.
          LogLevel VERBOSE

          # Log sftp level file access (read/write/etc.) that would not be easily logged otherwise.
          Subsystem sftp /usr/lib/sftp-server -f AUTHPRIV -l INFO

          PermitRootLogin prohibit-password

          UsePAM yes

          PrintMotd no

          PrintLastLog yes

        sshd_config_d:
          - name: change-port
            config: |
              Port 2222
